DOC: Corrected broken usage link
nhcarrigan/discord-rpc pull request #4
Opened 2021-02-09 12:42 UTC by 96RadhikaJadhav

# Pull Request

## Description:

 

Corrected broken usage link in README.md.

## Related Issue:

Closes #3 .

2021-02-09 16:22 UTC, nhcarrigan requested changes

2021-02-09 16:22 UTC, nhcarrigan commented on README.md
> +To see how to set up your own RPC, view our [usage instructions](https://github.com/nhcarrigan/discord-rpc#creating-your-own).
```suggestion
To see how to set up your own RPC, view our [usage instructions](./USAGE.md).
```
Linking to the same section of the README doesn't accomplish much. 🙂 

As discussed in the issue, we should only need to change the casing of the file extension to resolve the broken link.

2021-02-11 02:16 UTC, 96RadhikaJadhav commented on README.md
> +To see how to set up your own RPC, view our [usage instructions](https://github.com/nhcarrigan/discord-rpc#creating-your-own).
Done :) .

2021-02-11 15:50 UTC, nhcarrigan approved these changes
Looks good to me.

2021-02-11 15:51 UTC, merged

2021-02-11 15:51 UTC, nhcarrigan commented
Congrats on your first pull request (PR).

Thank you for your contribution to the page. We are happy to accept these changes and look forward to future contributions.

2021-02-11 15:51 UTC, nhcarrigan commented
@all-contributors please add @96RadhikaJadhav for docs